[package]
name = "mirage-tank"
version = "0.2.3"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"

[dependencies.image]
version = "0.21.1"
default-features = false
features = ["jpeg", "png_codec", "webp", "bmp"]
